---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: folding-at-home
  namespace: folding-at-home
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: folding-at-home
  chart:
    git: git@github.com:BigRedS/flux
    path: charts/folding-at-home
    ref: master
  values:
    image:
      repository: johnktims/folding-at-home
      tag: 7.6.13
    replicaCount: 5
